// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
//import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for android - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCKOnz5hNAcI2dUAH6ENA99E6cW5AgldV0',
//     appId: '1:1014022094930:web:8dec48ff82887288969f8b',
//     messagingSenderId: '1014022094930',
//     projectId: 'loginapp-527ba',
//     authDomain: 'loginapp-527ba.firebaseapp.com',
//     storageBucket: 'loginapp-527ba.appspot.com',
//     measurementId: 'G-PM12X3F3L2',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCD8ngbccXXL1oumeDQGgoLDicWkUWBGPI',
//     appId: '1:1014022094930:ios:6178654cc29964a4969f8b',
//     messagingSenderId: '1014022094930',
//     projectId: 'loginapp-527ba',
//     storageBucket: 'loginapp-527ba.appspot.com',
//     iosBundleId: 'com.example.myapp',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCD8ngbccXXL1oumeDQGgoLDicWkUWBGPI',
//     appId: '1:1014022094930:ios:1e3ca6399a41699a969f8b',
//     messagingSenderId: '1014022094930',
//     projectId: 'loginapp-527ba',
//     storageBucket: 'loginapp-527ba.appspot.com',
//     iosBundleId: 'com.example.myapp.RunnerTests',
//   );
// }


